### PR TITLE
small cleanup EntityWheel.java

### PR DESCRIPTION
**Pull request by xdeadstokex**

### CODE REVIEW

**Comment by GoldSloth** [comment]
I used to be a
```Java
access type field(params) {
}
```

Guy but I'm more of a 
```Java
access type field(params)
{
}
```

guy now. It's easier to see the start of a block of code from an opening {, espescially if the other formatting is off for some reason.

**Comment by xdeadstokex** [comment]
@GoldSloth I base on modelrendererturbo.java lol, since the format of the code is off for every file, so I chose the most important file to base on. Was finding what caused wheel to bounce constantly on ground, tried to find here but no result, the code cleanup was just "conveniently" done.

**Comment by Unknown025** [comment]
This looks less readable than before. I'm fine with switching to a convention where the open curly brace is on its own line, I've always just adhered to IntelliJ's default formatter which uses the inline curly brace format. The problem with the changes in this PR is that besides being less readable, there isn't a space between the method name and the open curly brace, which to me just looks lazy.

I'm not against cleaning up messy code, but this looks messier than before without any other substance.

**Comment by xdeadstokex** [comment]
@Unknown025 ok then I will close this pull, but there is an skipable if (vehicle==NULL) return; at onUpdate() method, you can change that.

**Pull request closed without merging**
