### PR TITLE
NPE fix

### PR DESCRIPTION
**Pull request by SecretAgent12**

### CODE REVIEW

**Comment by Unknown025** [comment]
Has there been confirmed a NPE here? According to Forge's source code, there *shouldn't* be a null value here:
image

**Comment by SecretAgent12** [comment]
Player11 has displayName "Player11", but on server with plugins Player11 has displayName "[Captain] Player11" and then **getPlayer(nickname)** returns _null_

**Comment by SecretAgent12** [comment]
displayName is not nickname, we should use commandSenderName

**Comment by Unknown025** [comment]
Ah...okay. So then shouldn't this line [here](https://github.com/Unknown025/Flans-Mod-Plus/blob/9be89f15ef3246d49b250981fa9f39398e837577/src/main/java/com/flansmod/common/teams/PlayerStats.java#L57) also  be changed? That file name will then change based on the nickname set via plugins.

**Comment by SecretAgent12** [comment]
agree

**Pull request closed without merging**
