### PR TITLE
Add bolt action and bonus regen settings

### PR DESCRIPTION
**Pull request by TheWillyJ**
**- Added bolt action model type**
boltCycleDistance, boltRotationAngle, boltRotationOffset
Works the same as pump but allows for rotation.
Example config:
    pumpDelayAfterReload = 65;
    pumpDelay = 10;
    pumpTime = 30;
    boltCycleDistance = 1.250F;
    boltRotationOffset = new Vector3f(0F,2.6F,0F);
    boltRotationAngle = 75F;

**- Added bonus health regen settings (Tested in sp and mp)**
bonusRegenTickDelay, bonusRegenFoodLimit, bonusRegenAmount
"Bonus regen interval", "Bonus regen food limit", "Bonus regen amount"

### CODE REVIEW

**Comment by GoldSloth** [comment]
This looks good, am I right in thinking that "bolts" were previously just rendered using pumps? So this makes a separate model group, but uses the pump animation settings as well as new animation settings?

**Comment by TheWillyJ** [comment]
> 

Correct

**Comment by GoldSloth** [comment]
Alright, I'd ask if you could include some documentation or an example model perhaps, but otherwise I'm happy with it

**Review by Unknown025 — APPROVED** [review]
Formatting changes for ModelGun seem pretty strange, though that might be just GitHub's way of displaying it. Everything else looks fine.

**Comment by GoldSloth** [comment]
I believe that's just GitHub, I don't know why it does that.

**Pull request merged**
