### PR TITLE
Small reload cancel improvements

### PR DESCRIPTION
**Pull request by pixelrider2000**
Changes:
- fixed bug where ammo wouldn't render for empty guns (e.g. RPGs)
- reload is now cancelled if slot is changed or item type is different

### CODE REVIEW

**Comment by GoldSloth** [comment]
Code looks good, however during testing I found an bug. Pretty easy to reproduce, just get a gun and hold right click, and it continues to reload over and over without ammo showing up.

Also, if you spam 'R' ammo will appear in the inventory without any reloading animation taking place.
https://streamable.com/fg52u4

**Comment by GoldSloth** [comment]
~~https://streamable.com/aqpids~~

~~Sorry, another one. Right clicking after reloading cancels reload animation here too.~~

Ignore this I was using an out of date version.

**Comment by pixelrider2000** [comment]
So the holding right click thing was caused by the QueuedReload ticking one tick more than the actual reload time, so you could initiate another reload in that one extra tick and therefore cancel the previous.

About the other 'bug'. I don't think it is a bug. 
When a reload is finished, you get the ammo that was previously in the gun back. In creative mode you can therefore spam reload and keep getting ammo since no ammo is consumed when you reload.
It is only just very noticeable on FULLY LOADED shotguns, because their reload time is (pretty much?) 0.
So you spam 'R' and keep getting ammo.

Maybe there is an argument to be made that you shouldn't get the old magazine back in creative mode, but idk...

**Comment by GoldSloth** [comment]
For the second one the bug is more that the reload animation doesn't play I think

**Comment by pixelrider2000** [comment]
I believe that's also not new. IIrc reload time is 0 when no shells are inserted. There being no animation would make sense in that case.

**Comment by pixelrider2000** [comment]
float reloadTime = singlesReload ? (type.getReloadTime(gunStack) / maxAmmo) * reloadCount : type.getReloadTime(gunStack);

Yeah. When reloadCount is 0 (shotgun is already full), reloadTime is also 0.

**Comment by GoldSloth** [comment]
Huh, interesting. The main reason you'd do that is to swap out shells I guess? Perhaps that's something we can add... Even just for a full reload when it's full already and ignore the vase of partial reload

**Comment by pixelrider2000** [comment]
Yeah I don't think getReloadTime works properly since it doesn't take partial shot gun reloads into account. 
There is no need to call this method anyway since reloadTime is already known, so I just replaced it.

This is why you had to wait the full reload before animations would play client-side

**Comment by GoldSloth** [comment]
Yeah that makes sense. Do you mind making another test build for this?

**Comment by pixelrider2000** [comment]
Until now, I didn't even now what forceReload was, so I didn't know it was important :)

**Pull request merged**
