### PR TITLE
[BugFix] Fix of a bug with a double hit (damage)

### PR DESCRIPTION
**Pull request by SecretAgent12**
sometimes a bullet could hit several hitboxes of one player (for example, legs and body) and as a result the player received 2 hits

### CODE REVIEW

**Comment by GoldSloth** [comment]
Hm, I think more information is needed about what this is trying to solve. 
If the two hits is legitimate (the bullet path intersects both hitboxes), the penetration system will handle it and stop the bullet if it can't penetrate further.
If the two hits are not legitimate (ie the hitboxes overlap somehow, this problem should be fixed by adjusting the hitboxes.

**Comment by SecretAgent12** [comment]
In our case, this is the first option, BUT what if bullet penetration is >3?

**Comment by GoldSloth** [comment]
Then the bullet goes through multiple hitboxes in the sam tick unless they're wearing armour to prevent it.. that's by design I guess.

**Comment by SecretAgent12** [comment]
and what if they wear armor, there is NOT enough penetration for the bullet to fly further?(for example, a barret with high penetration against weak armor)

**Comment by SecretAgent12** [comment]
we are trying to set up penetration and damage for our server, according to our idea, there is a certain rifle that penetrates a player in armor through, BUT does not cause only 16 damage when hit in the body (but the bullet flies further).
that is, the idea is for the player to make his way in any case, but the oneshot only when hit in the head.
but sometimes we bullet touches 2 hitboxes at once and it turns out that the player receives equal damage 16 х 1 + 16 х 0.75 = 28

**Comment by GoldSloth** [comment]
> and what if they wear armor, there is NOT enough penetration for the bullet to fly further?(for example, a barret with high penetration against weak armor)

Then the penetration system **should** stop the bullet from penetrating further or doing anymore damage in this tick. If it doesn't, then that's a bug to fix elsewhere.

**Pull request closed without merging**
