### PR TITLE
NeedsFuel Config Option for Driveables

### PR DESCRIPTION
**Pull request by conman180**
## Description of changes
Added Config option for if the driveable needs fuel or not. (From trello board)
Has a roundabout way of doing it but gets the job done.
if enabled, fuel will always be in the tank
Has a small fail-safe if someone deliberately sets the tank size to 0 to avoid crashes
if tankSize is 0, tankSize=1

## Intended usage in Content Packs/Users of the mod
Manually powered vehicles/ "solar" powered vehicles that wouldnt need fuel in real life
e.i.
bicycles, skateboards. rickshaw, etc.

## Compatibility
shouldn,t break anything. new feature

## Other
in the future could have it also remove the fuel display when driving.

### CODE REVIEW

**Comment by GoldSloth** [comment]
Looks pretty good, only request I would make is to set needsfuel to false if the fuel tank size is set to -1, iirc that's a feature done by FM++ first so it'd be good to keep them compatible imo.

Otherwise, my only reservation is testing: we need to be sure that planes, vehicles, tanks, helicopters work properly - including things like tanks turning and vehicles going backwards.

**Comment by GoldSloth** [comment]
This is the changelog talking about the fuelling features there. https://github.com/ZedStudios98/Flans-Mod-Plus-Plus/releases/tag/v1.1.1

**Review by GoldSloth — CHANGES_REQUESTED** [review]
Sorry, I'm having difficulty understand how this works - if there's 0 or less fuel tank size, it'll set the fuel tank size to 1, which mean fuel tank size of -1 goes to 1, so the vehicle will need fuel.

It'd be good to make sure the previous behaviour of FuelTankSize 0 is kept too, as some packs use that in things like stationary artillery as vehicles.

Also, it'd be good to keep all the logic inside the isEngineActive function, so like:

return (driverIsCreative OR fuelInTank OR !needsFuel OR fueldTankSize == -1) AND engineStarted

And drop the <= 0, as I'm not sure that's needed.

Sorry to sound quite negative, please don't be put off. And sorry if I've missed anything or misunderstood the logic.

**Comment by conman180** [comment]
Sorry about the confusion. I thought merging would erase my fist way of doing it. The edits i made after were just a port from FM++
The way it currently works with the latest commits is this
for planes: canThrust = "in Creative", "fuelTankSize is 0 or less", or "normal fuel system"
same goes for vehicles.
If you want I can Close this PR, reset my version and redo it.

**Comment by conman180** [comment]
will open one with the proper edits

**Pull request closed without merging**
