### PR TITLE
New Additional Flight Model

### PR DESCRIPTION
**Pull request by conman180**
## Description of changes
Features: 
-New Flight Controller option: New flight Physics system built off of the old one and a couple ports from another version
-Old flight controller is and option and is default. User user must activate it thru configs to access.
-Credit to LabJac for shoot down aesthetics
-Big thanks to GoldSloth for the help and advice
-New Config Options
NewFlightControl: boolean. true enables new flight model. "default false"
Supersonic: Boolean, determines if plane is rated for speeds higher than 2.0"sound barrier." Punishes over speeding in low performance planes. (No more biplanes contending w/jets) "default false"
MaxThrust: Replaces MaxThrottle for planes(sort of). Units in 10s of kg. "default 50"
MaxSpeed: Limits speed to whatever its set to in Blocks/tick 
TakeoffSpeed: Sets speed that plane will lift off ground. Blocks/tick
Mass: kg "default 1000"
Wing Area: in meters squared. playes can apply real world counterpart's or calculate it by gettin the area"pixels" of top faces of one wing then dividing by 16.

## Intended usage in Content Packs/Users of the mod
Better Flight Physics
Planes no longer all act the same

## Compatibility
To make use of new features to the fullest, plane configs should be updated. However nothing will break unless someone sets up a config poorly

## Other
High Thrust/mass ration act erratic when at low speeds and only one wheel is on ground. Ei MaxThrust 200 Mass 1000

### CODE REVIEW

**Comment by GoldSloth** [comment]
This looks really good, I'm away for this weekend though so it'll be a couple of days before I can merge it. Thanks for your work :)

**Comment by GoldSloth** [comment]
Awesome! I've had a chance to look through it fully and it all looks pretty good - minor tweaks that could be made format wise, but I'm not going to worry about that too much. Stuff like if (condition==false) can be replaced with if(!condition).

Only two questions I have: Has labjac approved the use of his code? I know the license situation supposedly allows it, but I'd like to make sure he's happy with it too.

Secondly, would you be able to add a wiki page describing what each of these new variables do, along with adding to the config reference? I think it'd be really helpful for a bit more detail and maybe graphs about how plane handling works, for future maintaining too :)

Awesome work, I can't wait to try it out 👍

**Comment by conman180** [comment]
On the Labjac Code:
No I haven't got Express permission. I have messaged him. I just haven't got any response back
Due to that i figured with the licensing that crediting should be enough. If you can get into contact with him it would be nice.

When I get time later today Ill start on the wiki.

**Comment by GoldSloth** [comment]
Lab says ok, so we should be good to go.

Do you want to add the config reference stuff before merging, or in a different PR?

For the wiki, I think you're able to create a new page in the wiki for this repo already, I'm not 100% sure how that works though

**Comment by conman180** [comment]
Ill add the config stuff before the merge. For the wiki, I could create the page but i wont let me edit it.

**Comment by GoldSloth** [comment]
Unsure how to manage that, I'll have to have a look

**Comment by GoldSloth** [comment]
@Unknown025 would you be able to have a look at this?
https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

Think this would be alright, alternatively we can grant contributor rights.

**Comment by Unknown025** [comment]
Alright, @conman180 should be able to edit it now.

**Comment by GoldSloth** [comment]
Awesome, thank you :)

**Comment by conman180** [comment]
Should be good to merge. wiki and Config reference are done.

**Comment by GoldSloth** [comment]
It doesn't look like changes to config reference are included, if you look under 'files changed'?

**Comment by conman180** [comment]
Might have done it in the wrong spot. I edited it on the main one I think because it said "Propose Changes" Does it show up there?

**Comment by GoldSloth** [comment]
It doesn't show up on your fork or this one, try changing the file from github on your fork, or on your computer locally and commit the change?

And I've poked around with the formatting of your wiki page, I hope that's alright - just wanted to make it fairly consistent with the other pages. Apart from that, the information there is great and well explained :)

**Comment by conman180** [comment]
Hmm.. Guess I can try again I remember editing it and clicking propose changes. dont know why its not showing up

**Comment by conman180** [comment]
Should show up now hopefully. don't know why it put my edits into another branch on my fork

**Comment by GoldSloth** [comment]
That looks great, thank you!

**Pull request merged**
