### PR TITLE
Prevent possible cast exception in EntityBullet

### PR DESCRIPTION
**Pull request by AntonIT99**
## Description of changes
Cast owner into EntityLivingBase instead of EntityPlayer

### CODE REVIEW

**Comment by GoldSloth** [comment]
This looks good, have you been able to test this out? Particularly upon death for the KillMessage.

**Comment by AntonIT99** [comment]
As far as I tested, there were no issue. The kill message also works fine. I will tell you if I ever discover a problem related to this change.

**Comment by GoldSloth** [comment]
Alright, thanks for this.

**Comment by Unknown025** [comment]
In that case, it'd make more sense to save the owner as `EntityLivingBase` instead.

**Comment by GoldSloth** [comment]
That's a good point, can you remind me what the difference between the two is?

**Comment by Unknown025** [comment]
`Entity` is the superclass for every entity in the game, while `EntityLivingBase` is a subclass of `Entity` and inherited by every living mob in the game (i.e. zombies, players, villagers, etc). However, `EntityLivingBase` is already passed in through the constructor of `EntityBullet`, so there's basically no reason to downcast to `Entity` in the first place.

**Comment by GoldSloth** [comment]
Yeah that makes sense. Thanks :)

**Pull request merged**
