### PR TITLE
added bullet damage modifiers

### PR DESCRIPTION
**Pull request by pixelrider2000**
I think there should be a way to make bullets weaker after they penetrated some stuff. This could also be used as a great balancing factor for block penetration especially.

The way it works (block penetration as an example):
A block hit subtracts a certain amount of penetration from the bullet. This loss of penetration is used to subtract damage from the bullet. If 'blockPenetrationEffectOnDamage' is less than 1, it reduces the effect of that penetration loss by set amount.

- playerPenetrationEffectOnDamage
- entityPenetrationEffectOnDamage
- blockPenetrationEffectOnDamage
- penetrationDecayEffectOnDamage

### CODE REVIEW

**Comment by GoldSloth** [comment]
The code for this looks good, but I'm wondering how it fits in otherwise - is this meant to work alongside the current penetration system, or instead of?

The theory behind the penetration system is the bullet's current penetration can be though of as its velocity in real life (although it's not ingame), if it has enough velocity to penetrate an object more than 70%, it'll do full damage - otherwise it'll do decreased damage.

So if a bullet passes through one player, it does full damage to them, the penetration decreases. Then it moves on to another player behind them, and it'll do reduced damage - only if it's unable to penetrate that player >70%.

====

Anyway, the pen system I implemented isn't great I'll be honest, it's a bit quirky - but imo we need to discuss how this fits in overall.

**Comment by pixelrider2000** [comment]
It's meant to work alongside of it. Really, I am just looking for damage reduction after penetration. 
I definitely see what you mean (that whole damage reduction system after a certain threshold), but that would make bullets move through everything with full damage, and only at the very end apply damage reduction, right? 
I have to admit, I like the current system. I think it's simple to work and do the math with.

My current implementation would allow for a bullet to shoot through multiple blocks of glass, but without retaining its damage. And that's something I quite like, and I think could benefit gameplay and balance.

Maybe this 70% rule could be a config option like 'realisticPenetrationDamage', for people who prefer that? At the end of the day, either system would be optional

**Comment by pixelrider2000** [comment]
I think, generally, the more flexible a system is, the better

**Comment by GoldSloth** [comment]
> but that would make bullets move through everything with full damage, and only at the very end apply damage reduction, right?

Yup. The bullet only does less than full damage if it can't penetrate more than 70%, and will then get stuck and not go any further.

I see the value in adding that affect yeah - I guess you could consider a .50 going through a stop sign, and another going through two stop signs. They'll probably both penetrate fully, but the one going through the second stop sign's going to make a smaller hole.

The difficult part is figuring out how to make it easily understandable - the current system confuses people enough already. 

To keep it all in one place, and keep the code clean I think it should be calculated at the same point of the current formula, ie when penetration occurs and it's deciding how much damage to do - rather than at each tick after it's hit something and is decrementing pen. 

The current formula is:

``damage*min(1, (bulletPen/targetPen)^3.5)``

We could add a term of ``penetrationLossPercentage=type.bulletPen - currentBulletPen``

And then add that to the formula: (This ignores the 70% rule, but it's easy to apply)
``damage*min(1. (bulletPen/targetPen)^3.5)*penetrationLossPercentage``

If that's too aggressive, then `sqrt(penetrationLossPercentage)` or doing `(0.5 + 0.5 * penetrationLossPercentage)` would make it lesser.

And configuration then decides whether to use the 70%, ^3.5 or penetrationLossPercentage or both. Potentially in some kind of ratio, but that might be too complicated.

**Comment by pixelrider2000** [comment]
I think this approach is generally a good idea (i.e. keeping everything clean and in one place), but I think it lacks some flexibility. If I understand correctly, then there would only be an option for whether or not damage is dependend on penetration or not (in all cases). If I only wanted the damage to decrease when going through blocks though, and not for players for example, I couldn't do that. 
But I think this would require the damage to be calculated when something is hit, and not when something is damaged because at that point, you'd have no idea what the bullet went through, and how much damage should ultimately be applied. 

Imagine the bullet travelled through two blocks and lost penetration (block damage drop off is not enabled though) and then hits a player. If we now calculate the damage, we would only see the penetration drop off, but not where it came from. 

I don't think that's ideal.

**Comment by GoldSloth** [comment]
I see what you mean - it wouldn't differentiate between the causes of lost penetration. In that case we'd either have to scale the damage at the time of hit (your solution), or record the penetration losses seperately and combine them when it does damage - again I'd rather the second to avoid having similar behaviour happenning in multiple places and times.

I did wonder if the target (ie armour, vehicle) could also decide how much it gets affected by pen loss? That means `playerPenetrationEffectOnDamage entityPenetrationEffectOnDamage` could vary based on target - ie not all vehicles behave the same. Though that's a bit more complicated.

**Comment by pixelrider2000** [comment]
I combined the damage reduction logic into one method now. Any further penetration damage reduction stuff (e.g. 70% rule) could now also simply be put into that method.

**Comment by GoldSloth** [comment]
This looks really good! That's pretty which what I envisioned. Thanks for tidying that up.

I'm happy to accept this now, once we've had reviews from others too - it'd be really helpful if you could write up a quick explanation to put in the wiki. I'm happy to add it to the Wiki if you write it, or give you permission to write there directly.

**Review by Unknown025 — APPROVED** [review]
Looks fine, though I'd be curious to see how much of a performance hit this would be over time.

**Comment by pixelrider2000** [comment]
> it'd be really helpful if you could write up a quick explanation to put in the wiki. I'm happy to add it to the Wiki if you write it, or give you permission to write there directly.

| PlayerPenetrationDamageEffect | Float | 0 | How much player penetration affects the damage of the bullet. 0 = no effect, 1 = full effect (if the bullet loses 20% of its penetration due to penetrating a player, its damage would decrease by 20% respectively) |
| EntityPenetrationDamageEffect | Float | 0 | How much entity penetration affects the damage of the bullet |
| BlockPenetrationDamageEffect | Float | 0 | How much block penetration affects the damage of the bullet |
| PenetrationDecayDamageEffect | Float | 0 | How much penetration decay affects the damage of the bullet |

**Comment by GoldSloth** [comment]
> > it'd be really helpful if you could write up a quick explanation to put in the wiki. I'm happy to add it to the Wiki if you write it, or give you permission to write there directly.
> 
> | PlayerPenetrationDamageEffect | Float | 0 | How much player penetration affects the damage of the bullet. 0 = no effect, 1 = full effect (if the bullet loses 20% of its penetration due to penetrating a player, its damage would decrease by 20% respectively) | | EntityPenetrationDamageEffect | Float | 0 | How much entity penetration affects the damage of the bullet | | BlockPenetrationDamageEffect | Float | 0 | How much block penetration affects the damage of the bullet | | PenetrationDecayDamageEffect | Float | 0 | How much penetration decay affects the damage of the bullet |

You can add this to the ConfigReference.md file.

But a wiki page would be helpful too imo, to explain how this works and what the difference is to the current system. And maybe an example calculation to show people how to do it by hand.

**Comment by pixelrider2000** [comment]
I added the following section to the penetration wiki: https://github.com/Unknown025/Flans-Mod-Plus/wiki/Penetration-System#penetration-damage-effects

Do you think that this makes it understandable?

**Comment by GoldSloth** [comment]
That's good, yeah. I think it'd be helpful to add that the effect stacks on top of the other penetration system, and is always active -  but defaults to no effect.

**Comment by pixelrider2000** [comment]
Would it be possible to merge this now?

**Comment by GoldSloth** [comment]
Sure, I was waiting for willy to review it but he hasn't been active for a bit.

**Comment by GoldSloth** [comment]
Looks like it needs to be merged via command line, I'll give that a go when I've got time next. Probably this weekend or tuesday/wednesday.

**Comment by GoldSloth** [comment]
I've effectively merged this with 02ec127, IDK how to use git though so I'll close this now. Thanks :)

**Pull request closed without merging**
