### PR TITLE
FuelTankSize 0 or less to dsable fuel requirement

### PR DESCRIPTION
**Pull request by conman180**
## Description of changes
Made it so driveables can function w/o fuel if their tank size is 0 or less

## Intended usage in Content Packs/Users of the mod
manual/solar vehicles.

## Compatibility
No breakages ive found

## Other
Tested, works for both vehicles and planes w/o affecting performance.

### CODE REVIEW

**Comment by conman180** [comment]
issues from earlier PR should be fixed now.

**Comment by GoldSloth** [comment]
Sorry to have to bring bad news again - it's still not quite there.
I believe the NeedsFuel config is not there, and the requirement for FuelInTank to disable fuel required is less than 0, not including zero.
For NeedsFuel, an alternative way of doing it would be to just set the FuelTankSize to -1, the issue there is that if FuelInTank is set afterwards, you have to ignore the value given if it's not -1. It just saves on an extra variable, it could be cleaner but idk.

If the pull request/commit stuff is still confusing, we can talk through it on discord tomorrow. Something that may help is the 'Files Changed' tab at the top, it shows exactly what changes are being proposed in the pull request - that's what I look at when I review PRs.

**Comment by conman180** [comment]
the NeedsFuel config option should be gone. That's what i tried to delete before. all that should be there is the code saying
If FuelTankSize is 0 or less, then the vehicle/plane doesn't need fuel to run.

**Comment by GoldSloth** [comment]
Ahh, that makes sense. Therefore, the only change needed imo is to change fuelInTank<=0 to just < so we don't include 0

**Comment by GoldSloth** [comment]
That looks great! All ready to go :)
I'll merge these changes in now.

Thank you for your work on it, and really sorry that it took this long to get to a state where we're both happy with it. I'll try and communicate a bit more clearly in future.

I'll add a bit in the config reference, since it's only a very small bit that needs to change.

**Comment by conman180** [comment]
Thanks. Apologies for the confusion as well.

**Pull request merged**
